spring:
  application:
    name: plan-puzzle

  profiles:
    default: local
    group:
      test: test
      local : local
      dev: dev

  config:
    import: "application-db.yml, application-security.yml"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace